#!/bin/sh

pid=`cat /tmp/httpd.pid`
/usr/bin/kill -s SIGINT $pid

pid=`cat /tmp/telnetd.pid`
/usr/bin/kill -s SIGINT $pid

pid=`cat /tmp/dab.pid`
/usr/bin/kill -s SIGINT $pid

pid=`cat /tmp/dabgps.pid`
/usr/bin/kill $pid

x=`ps -C darkice`
pid=`echo $x | cut -f5 -d' '`
/usr/bin/kill $pid

x=`ps -C gpsd`
pid=`echo $x | cut -f5 -d' '`
/usr/bin/kill $pid

